# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4dbf6708fa64c70ac1c2f61304aff58c79cb25ed4e07f57bd1e19d62f12c99e57ced3924a895d4530442f8136f46e6b46f6e1c52f8a9adb623a232619c5b610e

test:
  secret_key_base: 9af03292a44808422d85309dff15a38b5d145de5a6a5b3d6c92affd580471823ef8a2b25715184abf35cc4db49614d878070a79ce95d84c2b69ea1e61681f720

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
